### ISSUE TITLE
Swank fails to start because clj-contrib/pprint doesn't compile

### ISSUE THREAD

**Issue by seh** [technomancy/swank-clojure#43]
When I attempt to start Swank (using the current tip version against the "master" branch), it fails with the following errors:

```
(require 'swank.swank)

(swank.swank/ignore-protocol-version "2011-03-13")

(do (.. java.net.InetAddress getLocalHost getHostAddress) nil)(swank.swank/start-server "/var/folders/GW/GW8s0M0DHCOwSFm5WtD8ok+++TI/-Tmp-/slime.244" :encoding "iso-latin-1-unix")

Clojure 1.3.0-master-SNAPSHOT
user=> CompilerException java.lang.ClassNotFoundException: swank/clj_contrib/pprint$fn__643$pretty_pr_code_STAR___644, compiling:(swank/clj_contrib/pprint.clj:34) 
user=> user=> CompilerException java.lang.Exception: No such var: swank.swank/ignore-protocol-version, compiling:(NO_SOURCE_PATH:3) 
user=> user=> nil
CompilerException java.lang.Exception: No such var: swank.swank/start-server, compiling:(NO_SOURCE_PATH:5) 
```

It looks like file <i>pprint.clj</i> is failing to compile due to the <code>pretty-pr-code*</code> macro not being defined as intended.

**Comment by seh** [comment]
Can anyone else reproduce this problem? I'm still experiencing it today, and have not been able to find a workaround.

**Comment by Munksgaard** [comment]
I have the same problem. I'm using cake to run a swank server. This is my project.clj:

``` clojure
(defproject test "0.0.1-SNAPSHOT"
  :description "TODO: add summary of your project"
  :dependencies [[org.clojure/clojure "1.3.0-alpha6"]
                 [org.clojure.contrib/server-socket "1.3.0-alpha4"]]
  :dev-dependencies [[swank-clojure "1.3.0-SNAPSHOT"]])
```

and when i run "lein swank" i get the following:

```
$ lein swank
Var *classpath* not marked :dynamic true, setting to :dynamic. You should fix this before next release!
Exception in thread "main" java.lang.ClassNotFoundException: swank/clj_contrib/pprint$fn__648$pretty_pr_code_STAR___649, compiling:(swank/clj_contrib/pprint.clj:34)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6255)
    at clojure.lang.Compiler.analyze(Compiler.java:6059)
    at clojure.lang.Compiler.analyze(Compiler.java:6020)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5422)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:4858)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3530)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6246)
    at clojure.lang.Compiler.analyze(Compiler.java:6059)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6236)
    at clojure.lang.Compiler.analyze(Compiler.java:6059)
    at clojure.lang.Compiler.access$100(Compiler.java:36)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:494)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6248)
    at clojure.lang.Compiler.analyze(Compiler.java:6059)
    at clojure.lang.Compiler.analyze(Compiler.java:6020)
    at clojure.lang.Compiler.eval(Compiler.java:6307)
    at clojure.lang.Compiler.load(Compiler.java:6738)
    at clojure.lang.RT.loadResourceScript(RT.java:344)
    at clojure.lang.RT.loadResourceScript(RT.java:335)
    at clojure.lang.RT.load(RT.java:413)
    at clojure.lang.RT.load(RT.java:385)
    at clojure.core$load$fn__4398.invoke(core.clj:5318)
    at clojure.core$load.doInvoke(core.clj:5317)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5132)
    at clojure.core$load_lib.doInvoke(core.clj:5169)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5207)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:604)
    at clojure.core$use.doInvoke(core.clj:5295)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at swank.commands.basic$eval611$loading__4293__auto____612.invoke(basic.clj:1)
    at swank.commands.basic$eval611.invoke(basic.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6303)
    at clojure.lang.Compiler.eval(Compiler.java:6294)
    at clojure.lang.Compiler.load(Compiler.java:6738)
    at clojure.lang.RT.loadResourceScript(RT.java:344)
    at clojure.lang.RT.loadResourceScript(RT.java:335)
    at clojure.lang.RT.load(RT.java:413)
    at clojure.lang.RT.load(RT.java:385)
    at clojure.core$load$fn__4398.invoke(core.clj:5318)
    at clojure.core$load.doInvoke(core.clj:5317)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5132)
    at clojure.core$load_lib.doInvoke(core.clj:5169)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5207)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$require.doInvoke(core.clj:5284)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at swank.swank$eval10$loading__4293__auto____11.invoke(swank.clj:11)
    at swank.swank$eval10.invoke(swank.clj:11)
    at clojure.lang.Compiler.eval(Compiler.java:6303)
    at clojure.lang.Compiler.eval(Compiler.java:6294)
    at clojure.lang.Compiler.load(Compiler.java:6738)
    at clojure.lang.RT.loadResourceScript(RT.java:344)
    at clojure.lang.RT.loadResourceScript(RT.java:335)
    at clojure.lang.RT.load(RT.java:413)
    at clojure.lang.RT.load(RT.java:385)
    at clojure.core$load$fn__4398.invoke(core.clj:5318)
    at clojure.core$load.doInvoke(core.clj:5317)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5132)
    at clojure.core$load_lib.doInvoke(core.clj:5169)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5203)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$require.doInvoke(core.clj:5284)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval6.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6303)
    at clojure.lang.Compiler.eval(Compiler.java:6293)
    at clojure.lang.Compiler.eval(Compiler.java:6294)
    at clojure.lang.Compiler.eval(Compiler.java:6270)
    at clojure.core$eval.invoke(core.clj:2680)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:31)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:31)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:36)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:36)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:36)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: swank/clj_contrib/pprint$fn__648$pretty_pr_code_STAR___649
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at clojure.lang.FnLoaderThunk.load(FnLoaderThunk.java:52)
    at clojure.lang.FnLoaderThunk.invoke(FnLoaderThunk.java:40)
    at clojure.lang.Var.invoke(Var.java:409)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.lang.Compiler.macroexpand1(Compiler.java:6159)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6234)
    ... 94 more
```

**Comment by Munksgaard** [comment]
There is no problem if i use clojure 1.3.0-alpha5 instead of alpha6 though.

**Comment by technomancy** [comment]
Pretty sure this has been fixed; reopen if it's still an issue.
