### ISSUE TITLE
SLIME doesn't work when autodoc is enabled

### ISSUE THREAD

**Issue by bbatsov** [technomancy/swank-clojure#49]
When slime-autodoc-mode is enabled I always get this exception:

[bozhidar@bozhidar-desktop ~/Projects]$ ~/.lein/bin/swank-clojure
user=> Connection opened on local port  4005
# <ServerSocket ServerSocket[addr=localhost/127.0.0.1,port=0,localport=4005]>

unreadable message: (:emacs-rex (swank:autodoc (quote ("printl" swank::%cursor-marker%)) :print-right-margin 164) "user" :repl-thread 5)

exception in read loop
java.lang.RuntimeException: java.lang.Exception: Invalid token: swank::
    at clojure.lang.RT.readString(RT.java:1263)
    at clojure.core$read_string.invoke(core.clj:2897)
    at swank.core.protocol$read_swank_message$fn__240.invoke(protocol.clj:44)
    at swank.core.protocol$read_swank_message.invoke(protocol.clj:43)
    at swank.core.connection$read_from_connection.invoke(connection.clj:59)
    at swank.core$read_loop.invoke(core.clj:337)
    at swank.swank$connection_serve$fn__1485$fn__1486.invoke(swank.clj:41)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:540)
    at swank.swank$connection_serve$fn__1485.doInvoke(swank.clj:38)
    at clojure.lang.RestFn.invoke(RestFn.java:398)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.Exception: Invalid token: swank::
    at clojure.lang.LispReader.interpretToken(LispReader.java:286)
    at clojure.lang.LispReader.read(LispReader.java:171)
    at clojure.lang.LispReader.readDelimitedList(LispReader.java:1060)
    at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
    at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
    at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
    at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
    at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
    at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
    at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
    at clojure.lang.LispReader.read(LispReader.java:145)
    at clojure.lang.RT.readString(RT.java:1260)
    ... 13 more

I guess nobody is willing to implement proper autodoc support for Clojure, but it would be nice if at least it didn't produce an error. People doing both CL and Clojure development have to constantly keep switching on and off this setting because of the issue.

**Comment by scottjad** [comment]
What version of slime are you using? I use one from 10-15-2009 commit﻿ 605f930 and autodoc works.

**Comment by bbatsov** [comment]
Latest CVS Slime. A lot of people are having the same problem. I'm aware that the only _supported_ SLIME is the one in ELPA, but it's useless for Common Lisp development...

**Comment by scottjad** [comment]
While technomancy doesn't want to follow a moving target, I suspect he'd be willing to upgrade the supported slime version if someone were to get it working bug free. AFAIK no one has done that yet. 

In the meantime opening a bug for everything not working in unsupported versions of slime probably isn't a good idea.

**Comment by scottjad** [comment]
btw what features in cvs slime are you missing from the old one? I'd be
curious if there are any that would apply to clojure.

Scott

**Comment by seh** [comment]
One thing I'd like to see ported to the Clojure version is "presentations".

I rarely use them to their full capability in CL, but even just being able to move the point to a previously returned (and printed) result and hit enter to insert an equivalent expression at the prompt is convenient. I'm so used to doing it that it's jarring when the Clojure REPL refuses to honor my request.

**Comment by bbatsov** [comment]
In the supported version it doesn't throw an error, but it simply does nothing. Can this be considered working? Normally function params will be highlighted by autodoc-mode.

**Comment by scottjad** [comment]
Yeah, I'm the person that added autodoc highlighting.
http://www.youtube.com/watch?v=lf_xI3fZdIg

Where are you loading autodoc from? I don't think it's in ELPA. Make sure
that the autodoc you're using is the same version as the supported slime, if
it still doesn't work for you please reopen.

I personally use slime from 10-15-2009 with autodoc every day, but yeah, if
it's not working with supported version that would be a bug. details
welcome.

Scott

**Comment by technomancy** [comment]
I have some functionality in the pipeline for making it a lot easier to sync versions between Clojure and Elisp. We should revisit this once it is fleshed out: https://github.com/technomancy/swank-clojure/blob/payload/src/leiningen/jack.clj and https://github.com/technomancy/clojure-mode/commit/e5ee0782e846a8e89e306a7f85e2f746934041a6#L0R832

**Comment by bbatsov** [comment]
jack-in is great! I definitely think that this is the proper way to go.
