### ISSUE TITLE
Connection closes after typing two characters.

### ISSUE THREAD

**Issue by kephas** [technomancy/swank-clojure#59]
I use swank-clojure 1.4.0-SNAPSHOT
After doing slime-connect and having the REPL, I typed "(+" and got disconnected from swank. Here's the output of `lein swank`:

$ lein swank
Connection opened on localhost port 4005.
unreadable message: (:emacs-rex (swank:autodoc (quote ("+" swank::%cursor-marker%)) :print-right-margin 155) "user" :repl-thread 4)
exception in read loop
java.lang.RuntimeException: java.lang.Exception: Invalid token: swank::
        at clojure.lang.RT.readString(RT.java:1263)
        at clojure.core$read_string.invoke(core.clj:2897)
        at swank.core.protocol$read_swank_message$fn__272.invoke(protocol.clj:46)
        at swank.core.protocol$read_swank_message.invoke(protocol.clj:45)
        at swank.core.connection$read_from_connection.invoke(connection.clj:59)
        at swank.core$read_loop.invoke(core.clj:348)
        at swank.swank$connection_serve$fn__1740$fn__1741.invoke(swank.clj:33)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:540)
        at swank.swank$connection_serve$fn__1740.doInvoke(swank.clj:30)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.Exception: Invalid token: swank::
        at clojure.lang.LispReader.interpretToken(LispReader.java:286)
        at clojure.lang.LispReader.read(LispReader.java:171)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1060)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1051)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:900)
        at clojure.lang.LispReader.read(LispReader.java:145)
        at clojure.lang.RT.readString(RT.java:1260)
        ... 13 more
exception in control loop
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:386)
        at swank.util.concurrent.mbox$receive.invoke(mbox.clj:28)
        at swank.core$control_loop.invoke(core.clj:401)
        at swank.swank$connection_serve$fn__1706$fn__1707$fn__1708.invoke(swank.clj:23)
        at swank.swank$connection_serve$fn__1706$fn__1707.invoke(swank.clj:22)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:540)
        at swank.swank$connection_serve$fn__1706.doInvoke(swank.clj:20)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Thread.java:636)

**Comment by scottjad** [comment]
What version (date) of slime are you using?

**Comment by kephas** [comment]
Scribit scottjad dies 28/07/2011 hora 18:29:

> What version (date) of slime are you using?

Debian package 1:20100722-1

As far as protocol is concerned, it says 2010-07-21.

Quickly,

## Pierre

pierre@nothos.net
OpenPGP 0xD9D50D8A

**Comment by scottjad** [comment]
swank-clojure only works with the old version of slime in marmalade. See https://github.com/technomancy/swank-clojure

**Comment by hugoduncan** [comment]
This particular error is triggered by the use of slime-autodoc - remove that from your contribs (it is part of slime-fancy) and you might get further…
