### ISSUE TITLE
Exception due to read-only files, "lein plugin install swank-clojure 1.3.4"

### ISSUE THREAD

**Issue by Myaushka** [technomancy/swank-clojure#98]
Crashes while trying to remove temporary files. Checked - the lein temp directory was read-only.

After I killed the process and reran the same command, worked with no issues, as you can see below.

**PS C:\Users\tatianar.emacs.d> lein plugin install swank-clojure 1.3.4**
[INFO] Unable to find resource 'swank-clojure:swank-clojure:jar:1.3.4' in repository central (http://repo1.maven.org/maven2)
Installing shell wrapper to C:\Users\tatianar.lein\bin\swank-clojure
Installing shell wrapper to C:\Users\tatianar.lein\bin\swank-clojure.bat
Downloading: org/clojure/clojure/1.2.1/clojure-1.2.1.pom from repository central at http://repo1.maven.org/maven2
Transferring 1K from central
Downloading: clj-stacktrace/clj-stacktrace/0.2.4/clj-stacktrace-0.2.4.pom from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
[INFO] Unable to find resource 'clj-stacktrace:clj-stacktrace:pom:0.2.4' in repository central (http://repo1.maven.org/maven2)
Downloading: clj-stacktrace/clj-stacktrace/0.2.4/clj-stacktrace-0.2.4.pom from repository clojars at http://clojars.org/repo/
Transferring 2K from clojars
Downloading: org/clojure/clojure/1.2.1/clojure-1.2.1.jar from repository central at http://repo1.maven.org/maven2
Downloading: clj-stacktrace/clj-stacktrace/0.2.4/clj-stacktrace-0.2.4.jar from repository central at http://repo1.maven.org/maven2
Transferring 3165K from central
Unable to locate resource in repository
[INFO] Unable to find resource 'clj-stacktrace:clj-stacktrace:jar:0.2.4' in repository central (http://repo1.maven.org/maven2)
Downloading: clj-stacktrace/clj-stacktrace/0.2.4/clj-stacktrace-0.2.4.jar from repository clojars at http://clojars.org/repo/
Transferring 6K from clojars
Copying 2 files to C:\Users\tatianar\AppData\Local\Temp\1\lein-eb78a936-55a4-4b94-8c4b-40024f1a5dbc\lib
Including swank-clojure-1.3.4.jar
Including clj-stacktrace-0.2.4.jar
Including clojure-1.2.1.jar
_Exception in thread "main" java.io.IOException: Couldn't delete C:\Users\tatianar\AppData\Local\Temp\1\lein-eb78a936-55a4-4b94-8c4b-400
24f1a5dbc\lib\clojure-1.2.1.jar (NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$script_opt.invoke(main.clj:270)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at clojure.lang.Var.invoke(Var.java:390)
        at clojure.lang.AFn.applyToHelper(AFn.java:193)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.io.IOException: Couldn't delete C:\Users\tatianar\AppData\Local\Temp\1\lein-eb78a936-55a4-4b94-8c4b-40024f1a5dbc\lib\cl
ojure-1.2.1.jar
        at clojure.java.io$delete_file.doInvoke(io.clj:413)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:19)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at leiningen.plugin$install.invoke(plugin.clj:70)
        at leiningen.plugin$plugin.invoke(plugin.clj:82)
        at clojure.lang.Var.invoke(Var.java:373)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.core$apply.invoke(core.clj:540)
        at leiningen.core$apply_task.invoke(core.clj:260)
        at leiningen.core$_main.doInvoke(core.clj:325)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$_main.invoke(core.clj:328)
        at user$eval42.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 11 more_
**Terminate batch job (Y/N)? ^C**
**PS C:\Users\tatianar.emacs.d> lein plugin install swank-clojure 1.3.4**
[INFO] Unable to find resource 'swank-clojure:swank-clojure:jar:1.3.4' in repository central (http://repo1.maven.org/maven2)
Installing shell wrapper to C:\Users\tatianar.lein\bin\swank-clojure
Installing shell wrapper to C:\Users\tatianar.lein\bin\swank-clojure.bat
Copying 2 files to C:\Users\tatianar\AppData\Local\Temp\1\lein-e5a27040-8986-4ab7-a029-0f4e450937a2\lib
Including swank-clojure-1.3.4.jar
Including clj-stacktrace-0.2.4.jar
Including clojure-1.2.1.jar
**Created swank-clojure-1.3.4.jar**
PS C:\Users\tatianar.emacs.d>

**Comment by ghost** [comment]
I'm having a similar problem on Windows 7 64bit, except I am unfortunately unable to install the plugin. It won't finish.

Exception in thread "main" java.io.IOException: Couldn't delete C:\Users\wkmanir
e\AppData\Local\Temp\lein-b0ae32a4-c982-4051-8265-7d9caca418bd\lib\cdt-1.2.6.2.j
ar (NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$script_opt.invoke(main.clj:270)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at clojure.lang.Var.invoke(Var.java:390)
        at clojure.lang.AFn.applyToHelper(AFn.java:193)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.io.IOException: Couldn't delete C:\Users\wkmanire\AppData\Local\
Temp\lein-b0ae32a4-c982-4051-8265-7d9caca418bd\lib\cdt-1.2.6.2.jar
        at clojure.java.io$delete_file.doInvoke(io.clj:413)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:17)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at leiningen.util.file$delete_file_recursively.doInvoke(file.clj:17)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at leiningen.plugin$install.invoke(plugin.clj:70)
        at leiningen.plugin$plugin.invoke(plugin.clj:82)
        at clojure.lang.Var.invoke(Var.java:373)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.core$apply.invoke(core.clj:540)
        at leiningen.core$apply_task.invoke(core.clj:263)
        at leiningen.core$_main.doInvoke(core.clj:329)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$_main.invoke(core.clj:332)
        at user$eval361.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 11 more

**Comment by Myaushka** [comment]
So you've tried killing it and rerunning? How about making the files read/write in temp while it's installing?

I can't remember the exact sequence of events, but one of the above steps did the trick for me.

**Comment by ghost** [comment]
I tried a few different things including what you've suggested. I've had no luck. I decided for the time being to use inferior-lisp mode on windows. I do tend to use Linux during me off-work hours and I've already set up my development environment on my Linux installation. Thank you for your suggestions.
